### ISSUE TITLE
OPENING ANACONA NAVIGATOR

### ISSUE THREAD

**Issue by katlego1609** [mpr213/lecture-notes#14]
"This application failed to start because it could not find or lod the Qt platform plugin"
"windows" in"".

Reinstalling the application may fix this problem. That is the error I get, and I have reinstalled it many times.

**Comment by lgpage** [comment]
This is unrelated to the lecture-notes.

Please ask for help on the following forum:
https://groups.google.com/a/continuum.io/forum/#!forum/anaconda

As a work-around please try running Jupyter Notebook as per the instructions on this video:
https://www.youtube.com/watch?v=JId0f7URtOQ&feature=youtu.be
