### ISSUE TITLE
Explain multiple returns as a special case of multiple assignment

### ISSUE THREAD

**Issue by alchemyst** [mpr213/lecture-notes#19]
At the moment students encounter tuple expansion for the first time as "multiple return" when discussing functions in Section 03. While a complete explanation of all the various expansions is perhaps too advanced at the beginning, I think it makes a little more sense to explain multiple return as a special case of multiple assignment, as it allows students to think of this as less of a "function thing" and more of an "assignment thing", since that's how the docs handle it.

**Comment by lgpage** [comment]
closed by #22
