### ISSUE TITLE
Images not rendering on GitHub

### ISSUE THREAD

**Issue by alchemyst** [mpr213/lecture-notes#4]
The images in the notebooks aren't rendering. I think they sandbox so that you have to use a path below the location of the notebook.

**Comment by lgpage** [comment]
This seems to only be a problem with .svg images

**Comment by lgpage** [comment]
.svg images not showing in .ipynb rendered files

> Thanks for reaching out! We've opened an issue internally to investigate this. I can't promise an ETA, but I'll let you know as soon as there's any news!
> 
> Cheers,
> GitHub Support
