### ISSUE TITLE
Update references from Python 3.5 to Python 3.6

### ISSUE THREAD

**Issue by alchemyst** [mpr213/lecture-notes#9]
If the students download Anaconda now, they will get a 3.6 download. There are no breaking changes, we should be able to search and replace 3.5 with 3.6.

**Comment by lgpage** [comment]
There are in any case very few references to 3.5, so it should be quick to update.

**Comment by lgpage** [comment]
I wonder if we shouldn't add a very short section on Python versions some where in the notes?
